---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: kewlfft.aur
    version: ">=0.9.0"
  - name: community.general
    version: ">=6.0.0"
