---
# Geoloc OS - Role-based system provisioning
# Main playbook that orchestrates all roles for system setup

- name: Setup Geoloc OS with role-based structure
  hosts: localhost
  become: false
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Display setup information
      debug:
        msg: "Starting Geoloc OS setup: Base + Desktop + Development + Extras"

  roles:
    - { role: base, tags: ["base"] }
    - { role: desktop, tags: ["desktop"] }
    - { role: development, tags: ["development"] }
    - { role: extras, tags: ["extras"] }
    - { role: system-hardening, tags: ["system-hardening"] }

  post_tasks:
    - name: Display completion message
      debug:
        msg: |
          Geoloc OS setup complete!

          Next steps:
          1. Reboot to ensure all services are running
          2. Set up your personal dotfiles repository
