---
# Desktop role packages - Hyprland desktop environment

hyprland_packages:
  - hyprland
  - hyprlock
  - hypridle
  - hyprpicker
  - waybar
  - mako
  - swaybg
  - wl-clipboard
  - grim
  - slurp
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - polkit-gnome
  - qt5-wayland
  - qt6-wayland
  - xorg-xwayland
  - sddm

hyprland_extensions:
  - hyprland-qtutils
  - hyprpolkitagent
  - hyprshot
  - kanshi
  - wl-clip-persist
  - wlr-randr
  - nwg-displays

font_packages:
  - ttf-font-awesome
  - noto-fonts
  - noto-fonts-emoji

fonts_extended:
  - noto-fonts-cjk
  - ttf-dejavu
  - ttf-liberation
  - ttf-firacode-nerd
  - ttf-jetbrains-mono-nerd

media_graphics:
  - gimp
  - imagemagick
  - imv
  - mpv
  - evince
  - mediainfo

browsers:
  - firefox

system_utils_extra:
  - plocate
  - clipse
  - blueberry

aur_packages:
  - zim-git
  - walker-bin
  - zen-browser-bin
  - brave-bin

# All packages for this role
packages: "{{ hyprland_packages + hyprland_extensions + font_packages + fonts_extended + media_graphics + browsers + system_utils_extra }}"

# AUR packages handled separately due to different installation method
aur_packages_list: "{{ aur_packages }}"